### PR TITLE
Added PKGBUILD

### PR DESCRIPTION
**Pull request by demostanis**
As proposed by #64 
Here's a PKGBUILD, I could not test it though, but it should work.

### CODE REVIEW

**Comment by demostanis** [comment]
I'm testing it, and it doesn't work.
Sorry for being retarded

**Comment by demostanis** [comment]
Sorry for those no sense commit messages

**Comment by demostanis** [comment]
How the fuck do I change an already-pushed commit message?

**Comment by demostanis** [comment]
There is a permission problem, I'm gonna try to fix that

**Comment by demostanis** [comment]
Oh god, VirtualBox is lagging as fuck

**Comment by demostanis** [comment]
Ohhh, I think the only issue was using `sudo` while copying files,
I'm gonna add a message which tells not to use `sudo` with `cp`.

**Comment by demostanis** [comment]
Damn it. It's finally working!

**Comment by eromatiya** [comment]
Thanks for this! I don't know much about creating a PKGBUILD, but can we shallow clone? The repo is too big if you clone it with all the history, so I think it's better if we use `--depth 1` or something.

**Comment by demostanis** [comment]
[This doesn't seem to be possible in a PKGBUILD](https://unix.stackexchange.com/questions/154919/how-to-modify-a-pkgbuild-which-uses-git-sources-to-pull-only-a-shallow-clone)

**Comment by demostanis** [comment]
It's working

**Comment by demostanis** [comment]
Will this ever get merged? What's needed left?

**Comment by eromatiya** [comment]
Thanks!

**Pull request merged**
