### PR TITLE
add pam support

### PR DESCRIPTION
**Pull request by RMTT**

### CODE REVIEW

**Comment by eromatiya** [comment]
Thank you for your contribution! I definitely love this feature.

**Comment by ildar** [comment]
Guys, what's that? You're adding binary libraries ?
%(

**Comment by RMTT** [comment]
> 
> Guys, what's that? You're adding binary libraries ? %(

yeah, lua seems cannot use PAM api drirectly .

**Comment by eromatiya** [comment]
> Guys, what's that? You're adding binary libraries ?

Uhm yeah. This is 1000x better than writing our lockscreen password in a plain text. Haha

**Comment by ildar** [comment]
1. source is not included. Plz  add Makefile also
2. the binary is arch-dependent
3. there ARE other ways. Did you not even consider? Just for example: have
the lib packaged in LuaRock and installed system-wide.

**Comment by RMTT** [comment]
> 1. source is not included. Plz add Makefile also

you can find sources on this issue #63  or this repo


> 2. the binary is arch-dependent

Maybe, just use libpam and libpam_misc(can remove now), and the "login" service


> 3. there ARE other ways. Did you not even consider? Just for example: have the lib packaged in LuaRock and installed system-wide.

I'm newbie to lua and , so don't use LuaRock.

**Pull request merged**
