### PR TITLE
Added volume control widget in top panel

### PR DESCRIPTION
**Pull request by danimateo**
Opens app set in `apps.lua`, someone recommended `pavucontrol` in an issue.

Top panel:

Pavucontrol:

### CODE REVIEW

**Comment by eromatiya** [comment]
Thanks for this but I don't think we need this right now. We can just launch pavucontrol using rofi or by just creating a keybind for it. Anyway, I'm planning to create a widget named `dynamic volume control`  using this https://github.com/manilarome/the-glorious-dotfiles/issues/52 . Thanks again :)

**Comment by danimateo** [comment]
Yeah, I made #52 haha. This was supposed to be a temporary wokaround, but you're right I guess, rofi is enough.

**Comment by ildar** [comment]
personally I am happy with pasystray in tray.

**Comment by eromatiya** [comment]
> Yeah, I made #52 haha. 

Yep, and it's pretty handy. 

> personally I am happy with pasystray in tray.

That's a good suggestion.

Conclusion: Having a widget to change the volume levels for each application is pretty neat, although hard to implement it's still possible. So right now let's stick to pavucontrol or psystray because I don't really know how to start with the widget.

**Comment by danimateo** [comment]
> personally I am happy with pasystray in tray.
> 

from what I can see the sys tray lets you select the streams only and the volume control opens `pavucontrol`, but it's good anyway.

**Pull request closed without merging**
