### PR TITLE
awesome/floppy make a screenshot module to replace binary

### PR DESCRIPTION
**Pull request by ArtemSmaznov**
- Only made the change for the floppy theme
- you can now add a new shortcut for `require('module.screenshot')('window')`
- as far as I can see this is exactly the same functionality as you had with the binaries but is a bit easier to follow

### CODE REVIEW

**Comment by eromatiya** [comment]
Hey can you please implement [this](https://github.com/manilarome/the-glorious-dotfiles/blob/f738311feda1365e1a8de92ca43426aff5096c40/config/awesome/floppy/binaries/snap#L41-L44)? Those lines prevents the script from creating a notification if the user cancelled the screenshot in area mode. And that's the reason why I use a shell script for screenshot.

**Comment by ArtemSmaznov** [comment]
let me see what I can do

**Comment by eromatiya** [comment]
Thanks! Good luck! It just checks if the file in `file_loc` exists. If not, don't copy to xclip and don't create a notification.

**Comment by ArtemSmaznov** [comment]
done

**Comment by eromatiya** [comment]
You're fast! Haha. Wait, I'll test it

**Comment by eromatiya** [comment]
LGTM! My only complaint is that the `screenshot_dir` is not an XDG compliant. I changed it to `'$(xdg-user-dir PICTURES)/Screenshots/'` but the `(gears.filesystem.file_readable(file_loc))` stops working. This is important because some people changes their `Pictures` directory to somewhere else like external drive.

**Comment by ArtemSmaznov** [comment]
I think I can make that work. Also I feel like I forgot to add the folder check and creation logic so will do as well

**Comment by ArtemSmaznov** [comment]
This is so weird. I tried getting the path to pictures using this:
```
awful.spawn.easy_async('xdg-user-dir PICTURES', function(stdout, stderr, reason, exit_code)
	local dir = stdout .. '/Screenshots/'
end
```
and it does return the path. But it puts a `?` after the xdg path and I cannot figure out why making it look like `/home/user/Pictures?/Screenshots`

I did add the logic for creating the Screenshot folder if it doesn't exists to my last commit but this question mark thing I don't know - might be a bug with `awful.spawn` or something like that.

Either way it might be alright to leave it up to the user to change the preferred directory. Or maybe you will have some idea why is there a `?` appended?

**Comment by ildar** [comment]
It's new line character in the command output.
BTW why not using this?
https://github.com/manilarome/the-glorious-dotfiles/issues/79#issuecomment-611549917

**Comment by eromatiya** [comment]
Yep that's probably a new line. Anyway, if you're having a really bad time, that's okay. @ildar's suggestion was to remove the *compiled* binaries, where is the only compiled right now is the PAM library for awesome. Previously, we have the compiled capschekcer binary so yeah.

**Comment by ArtemSmaznov** [comment]
Let me try tip suggested by @ildar as I count find it myself before for some reason.

Btw tnx for that @ildar I actually wanted to find something like this

**Comment by ArtemSmaznov** [comment]
@ildar `get_xdg_data_dirs()` points to `/usr/share` folder. I am starting to think it is impossible to get the Pictures directory without using the shell.
If anyone has any suggestions how I can get around that `?` issue with shell I am happy to fix that but as it stands I don't really know how to approach it.
@manilarome would you like to merge this or the path thing is a deal breaker?

**Comment by ArtemSmaznov** [comment]
wait

**Comment by ArtemSmaznov** [comment]
ok this should be it. A bit less elegant but seems to work

**Comment by ildar** [comment]
I still don't understand how the ‘maim’ is better then xclip? Adding new
dependencies isn't so great.

**Comment by ArtemSmaznov** [comment]
I didn't add maim - it was already there. All I did was refactor the code to use awesome libraries instead if shell commands where I could

**Comment by ArtemSmaznov** [comment]
@manilarome it is ready in case you haven't noticed this

**Comment by eromatiya** [comment]
Sorry for the delay! I'll test it now

**Comment by eromatiya** [comment]
Thanks!

**Pull request merged**
